# NOTE: only this workflow should be allowed to call the metadata repo
# or else those workflows can claim to dispatch events for other repos
# which is a security risk.
# This repo should be private.
    # secrets:
    #   METADATA_PAT:
    #     required: true # this is actually injected via github actions secrets relay env in repo B


name: Relay to Metadata

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      METADATA_PAT:
        required: true

jobs:
  relay:
    # don't run on tags to _this_ repo // could maybe check github.repository != "TRAINFACED/b" instead....
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source repo (Repo A)
        uses: actions/checkout@v4

      - name: Prepare payload
        id: payload
        run: |
            payload=$(jq -nc -c \
              --arg repo "${{ github.repository }}" \
              --arg tag "${{ inputs.tag }}" \
              '{repo: $repo, tag: $tag}')
            echo "payload=$payload" >> $GITHUB_OUTPUT

      - name: Dispatch to Metadata
        run: |
              echo "Dispatching to Metadata repo..."
              response=$(mktemp)
          
              status=$(curl -s -o "$response" -w "%{http_code}" -X POST \
                -H "Authorization: Bearer ${{ secrets.METADATA_PAT }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/TRAINFACED/metadata/dispatches \
                -d "$(jq -nc \
                      --argjson client_payload '${{ steps.payload.outputs.payload }}' \
                      '{event_type: "new-release", client_payload: $client_payload}')")
          
              if [ "$status" -ne 204 ]; then
                echo "❌ Dispatch failed with status code $status"
                echo "--- response body ---"
                cat "$response"
                echo "----------------------"
                exit 1
              fi
          
              echo "✅ Dispatch succeeded with status $status"