# NOTE: only this workflow should be allowed to call the metadata repo
# or else those workflows can claim to dispatch events for other repos
# which is a security risk.
# This repo should be private.

name: Relay to Metadata

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  relay:
    environment: relay # use secrets from _THIS_ repo.  This to to prevent other repos from dispatching to metadata directly.
    # don't run on tags to _this_ repo // could maybe check github.repository != "TRAINFACED/b" instead....
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (Repo A)
        uses: actions/checkout@v4

      - name: Load config.json
        id: files
        run: |
          echo "config=$(jq -c . < config.json)" >> $GITHUB_OUTPUT
          echo "baton_capabilities=$(jq -c . < baton_capabilities.json)" >> $GITHUB_OUTPUT

      - name: Prepare payload
        id: payload
        run: |
            payload=$(jq -nc -c \
              --arg sender "${{ github.repository }}" \
              --arg version "${{ inputs.tag }}" \
              --argjson config '${{ steps.files.outputs.config }}' \
              --argjson baton_capabilities '${{ steps.files.outputs.baton_capabilities }}' \
              '{sender: $sender, version: $version, config: $config, baton_capabilities: $baton_capabilities}')
            echo "payload=$payload" >> $GITHUB_OUTPUT

      - name: Dispatch to Metadata
        run: |
              echo "Dispatching to Metadata repo..."
              response=$(mktemp)
          
              status=$(curl -s -o "$response" -w "%{http_code}" -X POST \
                -H "Authorization: Bearer ${{ secrets.METADATA_PAT }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/TRAINFACED/metadata/dispatches \
                -d "$(jq -nc \
                      --argjson client_payload '${{ steps.payload.outputs.payload }}' \
                      '{event_type: "new-release", client_payload: $client_payload}')")
          
              if [ "$status" -ne 204 ]; then
                echo "❌ Dispatch failed with status code $status"
                echo "--- response body ---"
                cat "$response"
                echo "----------------------"
                exit 1
              fi
          
              echo "✅ Dispatch succeeded with status $status"